spring:
  application:
    name: simple-client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    heartbeat-executor-thread-pool-size: 2
  instance:
    status-page-url-path: /info
    health-check-url-path: /health
server:
  port: ${PORT}