spring:
  application:
    name: sample-users-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    heartbeat-executor-thread-pool-size: 2
  instance:
    status-page-url-path: /info
    health-check-url-path: /health
server:
  port: ${PORT}

clients-service:
  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ServerListRefreshInterval: 60000
    DeploymentContextBasedVipAddresses: simple-client
